weights: /hy-tmp/models/st-gcn_2d/SEA_G_2D/SEA_G_2D.pt
model_fps: 30

# model
model: net.st_gcn_new.Model
model_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'customer_vitpose'
    strategy: 'spatial'
    
# training
device: [0]